packageExtensions:
  "@graphql-codegen/cli@^2.12.0":
    dependencies:
      ts-node: ">=10"
    peerDependencies:
      "@types/node": "*"
      typescript: ">=3"
  "@n1ru4l/graphql-live-query@^0.10.0":
    dependencies:
      tslib: "*"
  apollo-server-micro@^3.10.2:
    peerDependencies:
      graphql: ^15.3.0 || ^16.0.0
  graphql-codegen-plugin-typescript-swr@^0.8.1:
    peerDependencies:
      react: ^16.11.0 || ^17.0.0 || ^18.0.0
  graphql-config@^4.3.5:
    peerDependencies:
      "@types/node": "*"
      typescript: ">=3"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
