packageExtensions:
  "@graphql-codegen/cli@^2.13.0":
    dependencies:
      ts-node: ">=10"
    peerDependencies:
      "@types/node": "*"
      graphql-tag: ^2.0.0
      typescript: ">=3"
  apollo-server-micro@^3.10.2:
    peerDependencies:
      graphql: ^15.3.0 || ^16.0.0
  graphql-codegen-plugin-typescript-swr@^0.8.3:
    peerDependencies:
      react: ^16.11.0 || ^17.0.0 || ^18.0.0
  graphql-config@^4.3.5:
    peerDependencies:
      "@types/node": "*"
      typescript: ">=3"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
