import { useMantineTheme } from '@mantine/core';
import useStyles from './PixelSlide.styles';
import type { FCC } from 'react';
import type { PixelSlideProps } from './index';

import Image from 'next/image';

/**
 * @param mediaQuery - The media query string generated by Mantine, which looks
 * like `@media (max-width:599.95px)`.
 * @returns The media query string without the `@media ` prefix.
 */
const getMediaQueryInfo = (mediaQuery: string) => mediaQuery.slice(mediaQuery.indexOf(' ') + 1);

const PixelSlide: FCC<PixelSlideProps> = (props) => {
    const { classes } = useStyles();

    const theme = useMantineTheme();

    return (
        <div className={classes.slide}>
            {props.image.alignment === 'right' && <div className={classes.text}>{props.children}</div>}
            <div className={classes.image}>
                <Image
                    fill
                    style={{ objectFit: 'contain' }}
                    sizes={`
                        ${getMediaQueryInfo(theme.fn.smallerThan('sm'))} 100px,
                        ${getMediaQueryInfo(theme.fn.smallerThan('md'))} 170px,
                        230px
                    `}
                    src={props.image.src}
                    alt={props.image.altText}
                    quality={100}
                />
            </div>
            {/* By default align to the left */}
            {props.image.alignment !== 'right' && <div className={classes.text}>{props.children}</div>}
        </div>
    );
};

export default PixelSlide;
